
#General configuration settings
[general]
	scaledFallDamage = true
	scaledMotion = true
	scaledReach = true
	scaledAttack = true
	scaledDefense = true
	scaledHealth = true
	scaledItemDrops = false
	scaledProjectiles = false
	scaledExplosions = false
	keepAllScalesOnRespawn = false
	accurateNetherPortals = true
	scalesKeptOnRespawn = []
	enableCommands = true
	enableDebugCommands = false

